#!/usr/bin/env python3
"""
FACILITATOR TOOLING — DO NOT SHARE WITH PARTICIPANTS
====================================================
Participants are required to build their own load generator with `agy`
(user_guide.md Phase 5, Step 2). This script exists so the facilitator can
calibrate scoring thresholds and sanity-check a project before the event.

Disneyland Park — Spanner Load Generator
========================================

Drives a *standardised* read and write load against your park's Spanner
instance so the leaderboard can measure what your cluster can actually sustain.

Why standardised matters
------------------------
Throughput measured with an ad-hoc script measures your laptop and your Wi-Fi,
not your Spanner instance. A single-threaded client that commits one row at a
time is bound by network round-trip time and will report roughly the same
number whether you are running 100 PUs or 10,000. Everybody runs this same
script with the same concurrency so the only variable left is how you sized and
designed your database.

Usage
-----
    # Write load: 60s of concurrent single-row commits
    python3 loadtest.py --project MY_PROJECT --mode write --duration 60

    # Read load: point lookups + graph traversals
    python3 loadtest.py --project MY_PROJECT --mode read --duration 60

    # Both, back to back (what the leaderboard audit expects)
    python3 loadtest.py --project MY_PROJECT --mode mixed --duration 90

Requirements: pip install google-cloud-spanner
"""
import argparse
import datetime
import decimal
import os
import random
import statistics
import sys
import threading
import time

os.environ.setdefault("SPANNER_DISABLE_BUILTIN_METRICS", "true")

from google.cloud import spanner  # noqa: E402

INSTANCE_ID = "disneyland"
DATABASE_ID = "agent-lab"

# Fixed so results are comparable across participants. Do not tune these to
# chase a score - the leaderboard grades how your instance responds to *this*
# load, not how hard you can hit it.
DEFAULT_THREADS = 32
DEFAULT_DURATION = 60


class Stats:
    """Thread-safe latency and count accumulator."""

    def __init__(self):
        self._lock = threading.Lock()
        self.latencies_ms = []
        self.ok = 0
        self.failed = 0
        self.first_error = None

    def record(self, elapsed_ms, ok=True, error=None):
        with self._lock:
            if ok:
                self.ok += 1
                self.latencies_ms.append(elapsed_ms)
            else:
                self.failed += 1
                if self.first_error is None and error is not None:
                    self.first_error = f"{type(error).__name__}: {str(error)[:300]}"

    def summary(self, wall_sec):
        with self._lock:
            lat = sorted(self.latencies_ms)
            n = len(lat)
            return {
                "ops": self.ok,
                "failed": self.failed,
                "qps": self.ok / wall_sec if wall_sec > 0 else 0.0,
                "p50": lat[int(n * 0.50)] if n else 0.0,
                "p95": lat[int(n * 0.95)] if n else 0.0,
                "p99": lat[int(n * 0.99)] if n else 0.0,
                "mean": statistics.mean(lat) if n else 0.0,
                "first_error": self.first_error,
            }


def _attraction_ids(db):
    """Grab real AttractionIDs so the load exercises the actual key space."""
    with db.snapshot() as snap:
        rows = list(snap.execute_sql("SELECT AttractionID FROM Attraction LIMIT 200"))
    return [r[0] for r in rows]


def write_worker(db, stop_at, stats, attraction_ids, worker_id):
    """One row per transaction. This is deliberately *not* batched.

    Batching 250 rows into one commit inflates rows/sec while hiding the
    transaction rate, and it stops the load from exercising Spanner's commit
    path - which is exactly the thing that scales with processing units.

    RunID is GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE), so it is
    deliberately omitted: letting Spanner assign it keeps the bit-reversed key
    distribution that prevents hotspotting on the interleaved child table.
    """
    while time.time() < stop_at:
        attraction_id = random.choice(attraction_ids)
        price = decimal.Decimal(str(round(random.uniform(12.0, 22.0), 2)))

        started = time.perf_counter()
        try:
            def _insert(txn):
                txn.execute_update(
                    "INSERT INTO AttractionRun "
                    "(AttractionID, RunTimestamp, TicketPrice) "
                    "VALUES (@aid, PENDING_COMMIT_TIMESTAMP(), @p)",
                    params={"aid": attraction_id, "p": price},
                    param_types={
                        "aid": spanner.param_types.INT64,
                        "p": spanner.param_types.NUMERIC,
                    },
                )

            db.run_in_transaction(_insert)
            stats.record((time.perf_counter() - started) * 1000.0, ok=True)
        except Exception as e:
            stats.record(0.0, ok=False, error=e)


def read_worker(db, stop_at, stats, attraction_ids, use_graph):
    """Point lookups plus, if a property graph exists, a traversal.

    Reads never land in AttractionRun, so they do not move the write-throughput
    number. They show up as Spanner CPU utilisation, which is what the
    efficiency audit reads.
    """
    while time.time() < stop_at:
        attraction_id = random.choice(attraction_ids)
        started = time.perf_counter()
        try:
            # multi_use=True is required: a default db.snapshot() is single-use
            # and raises "Cannot re-use single-use snapshot" on the second
            # execute_sql, which silently failed 100% of read iterations.
            with db.snapshot(multi_use=True) as snap:
                list(snap.execute_sql(
                    "SELECT a.AttractionID, a.Name, p.Name "
                    "FROM Attraction a JOIN DisneylandPark p ON a.ParkID = p.ParkID "
                    "WHERE a.AttractionID = @aid",
                    params={"aid": attraction_id},
                    param_types={"aid": spanner.param_types.INT64},
                ))
                if use_graph:
                    list(snap.execute_sql(
                        "GRAPH DisneylandGraph "
                        "MATCH (a:Attraction)-[:Path]->(b:Attraction) "
                        "RETURN a.Name AS src, b.Name AS dst LIMIT 25"
                    ))
            stats.record((time.perf_counter() - started) * 1000.0, ok=True)
        except Exception as e:
            stats.record(0.0, ok=False, error=e)


def detect_graph(db):
    try:
        with db.snapshot() as snap:
            rows = list(snap.execute_sql(
                "SELECT property_graph_name FROM information_schema.property_graphs"
            ))
        return len(rows) > 0
    except Exception:
        return False


def run_phase(label, target, db, duration, threads, stats, attraction_ids, extra):
    stop_at = time.time() + duration
    workers = []
    for i in range(threads):
        t = threading.Thread(
            target=target,
            args=(db, stop_at, stats, attraction_ids) + extra + ((i,) if target is write_worker else ()),
            daemon=True,
        )
        t.start()
        workers.append(t)

    started = time.time()
    while any(w.is_alive() for w in workers):
        time.sleep(2)
        elapsed = time.time() - started
        remaining = max(0, duration - elapsed)
        snap = stats.summary(max(0.001, elapsed))
        sys.stdout.write(
            f"\r  {label}: {snap['ops']:>7,} ops | "
            f"{snap['qps']:>7.1f} ops/s | p95 {snap['p95']:>6.1f} ms | "
            f"{remaining:>4.0f}s left   "
        )
        sys.stdout.flush()
    print()
    return time.time() - started


def main():
    ap = argparse.ArgumentParser(description="Spanner load generator for the Disneyland lab")
    ap.add_argument("--project", required=True, help="Your GCP project ID")
    ap.add_argument("--mode", choices=["write", "read", "mixed"], default="mixed")
    ap.add_argument("--duration", type=int, default=DEFAULT_DURATION,
                    help=f"Seconds per phase (default {DEFAULT_DURATION})")
    ap.add_argument("--threads", type=int, default=DEFAULT_THREADS,
                    help=f"Concurrent clients (default {DEFAULT_THREADS}; "
                         "changing this makes your result incomparable)")
    args = ap.parse_args()

    client = spanner.Client(project=args.project)
    inst = client.instance(INSTANCE_ID)
    inst.reload()
    db = inst.database(DATABASE_ID)

    pus = inst.processing_units
    print("=" * 66)
    print(f"  Disneyland Load Generator — {args.project}")
    print(f"  Instance: {INSTANCE_ID} @ {pus} PUs   Threads: {args.threads}")
    print("=" * 66)

    attraction_ids = _attraction_ids(db)
    if not attraction_ids:
        print("  ! No rows in Attraction. Seed your park before load testing.")
        return 1
    print(f"  Key space: {len(attraction_ids)} attractions")

    has_graph = detect_graph(db)
    print(f"  Property graph: {'yes' if has_graph else 'no (read phase will skip traversals)'}")
    print()

    results = {}

    if args.mode in ("write", "mixed"):
        stats = Stats()
        wall = run_phase("write", write_worker, db, args.duration,
                         args.threads, stats, attraction_ids, ())
        results["write"] = stats.summary(wall)

    if args.mode in ("read", "mixed"):
        stats = Stats()
        wall = run_phase("read ", read_worker, db, args.duration,
                         args.threads, stats, attraction_ids, (has_graph,))
        results["read"] = stats.summary(wall)

    print()
    print("=" * 66)
    print(f"  RESULTS @ {pus} PUs")
    print("=" * 66)
    for phase, s in results.items():
        print(f"  {phase.upper():<6} {s['ops']:>8,} ops  "
              f"{s['qps']:>8.1f} ops/s  "
              f"p50 {s['p50']:>6.1f}  p95 {s['p95']:>6.1f}  p99 {s['p99']:>6.1f} ms"
              + (f"  ({s['failed']} failed)" if s["failed"] else ""))
        if s["first_error"]:
            print(f"         first error: {s['first_error']}")
    print()
    print("  Scale your instance and run this again to compare. Watch p95:")
    print("  if latency drops and ops/s rises, the extra compute is doing work.")
    print("  If ops/s barely moves, you are paying for capacity you cannot use.")
    print()
    print(f"  Spanner CPU utilisation: console.cloud.google.com/spanner/instances/"
          f"{INSTANCE_ID}/details/metrics?project={args.project}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
