variable "project_id" {
  description = "The target ephemeral GCP project allocated for the participant"
  type        = string
}

variable "region" {
  description = "The target deployment region"
  type        = string
}

variable "vpc_id" {
  description = "The VPC network identifier generated by the 00-core-infra baseline"
  type        = string
}

variable "private_vpc_connection_id" {
  description = "The private service connection ID from the core network"
  type        = string
}

variable "iap_member" {
  description = "The IAM member string for the participant (e.g., user:devstar@gcplab.me)"
  type        = string
}
